<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Functions\TabloAspose.cs" />
    <Compile Remove="Objects\AltSurecDto.cs" />
    <Compile Remove="Objects\StratejikPlanDto.cs" />
    <Compile Remove="Objects\StratejikPlanHedefDto.cs" />
    <Compile Remove="Objects\SurecDto.cs" />
    <Compile Remove="Objects\TanimBirimDto.cs" />
    <Compile Remove="Objects\TanimKoordinatorlukDto.cs" />
    <Compile Remove="Objects\YetkiDto.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GemBox.Spreadsheet" Version="47.0.1298" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="5.0.0" />
    <PackageReference Include="MimeKit" Version="3.1.1" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.2.12" />
  </ItemGroup>

</Project>
