<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Functions\TanimAmacService.cs" />
    <Compile Remove="Functions\TanimBirimKoordinatorlukService.cs" />
    <Compile Remove="Functions\TanimHedefService.cs" />
    <Compile Remove="Functions\TanimSehirService.cs" />
    <Compile Remove="Functions\TanimUlkeService.cs" />
    <Compile Remove="Interfaces\ITanimAmacService.cs" />
    <Compile Remove="Interfaces\ITanimBirimKoordinatorlukService.cs" />
    <Compile Remove="Interfaces\ITanimHedefService.cs" />
    <Compile Remove="Interfaces\ITanimSehirService.cs" />
    <Compile Remove="Interfaces\ITanimUlkeService.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="5.0.10" />
    <PackageReference Include="Quartz.AspNetCore" Version="3.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Risk.net.Data\Risk.net.Data.csproj" />
    <ProjectReference Include="..\Risk.net.Utilities\Risk.net.Utilities.csproj" />
  </ItemGroup>

</Project>
